name: macOS universal build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-universal:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build arm64 binary
        run: |
          pyinstaller --onefile --name MeetingScheduler-arm64 main.py

      - name: Build x86_64 binary
        run: |
          arch -x86_64 pyinstaller --onefile --name MeetingScheduler-x86_64 main.py

      - name: Create universal binary
        run: |
          mkdir -p dist/universal
          lipo -create dist/MeetingScheduler-arm64 dist/MeetingScheduler-x86_64 -output dist/universal/MeetingScheduler

      - name: Upload universal binary
        uses: actions/upload-artifact@v4
        with:
          name: MeetingScheduler-universal
          path: dist/universal/MeetingScheduler
