name: macOS build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build app bundle
        run: pyinstaller --windowed --name MeetingScheduler main.py

      - name: Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: MeetingScheduler-macos
          path: dist/MeetingScheduler.app